FROM alpine:latest@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4

RUN apk --update --no-cache add \
    tar \
    rsync \
    ca-certificates \
    openssh \
    git \
    bash \
    gawk \
    procps \
    coreutils

COPY ./ /backup-utils/
WORKDIR /backup-utils

RUN chmod +x /backup-utils/share/github-backup-utils/ghe-docker-init

ENTRYPOINT ["/backup-utils/share/github-backup-utils/ghe-docker-init"]
CMD ["ghe-host-check"]
